### ISSUE TITLE
Error including library

### ISSUE THREAD

**Issue by nflaum** [khoih-prog/STM32_TimerInterrupt#1]
Hello, when I run the code below I get the following error: 

> WARNING: library STM32_TimerInterrupt claims to run on stm32 architecture(s) and may be incompatible with your current board which runs on STM32F1 architecture(s).

> error: #error This code is designed to run on STM32F/L/H/G/WB/MP1 platform! Please check your Tools->Board setting.

```
#include <STM32TimerInterrupt.h>
#include <STM32_ISR_Timer.h>

void setup() {
}

void loop() {
}
```
![image](https://user-images.githubusercontent.com/71182580/100181391-f7a5bd00-2e8e-11eb-83ac-baa7ddf69f09.png)

**Comment by khoih-prog** [comment]
The [**Roger Clar's STM32 core**](https://github.com/rogerclarkmelbourne/Arduino_STM32)  you're using is not currently supported.I don't know in the future if I can add that core into the supported list.

You have to use this [**Arduino_Core_STM32**](https://github.com/stm32duino/Arduino_Core_STM32).

Convert to new core by following this intructions in [**Getting Started**](https://github.com/stm32duino/Arduino_Core_STM32#getting-started)

**Comment by nflaum** [comment]
Thanks
