### ISSUE TITLE
STM32 2.4MHz PWM

### ISSUE THREAD

**Issue by nflaum** [khoih-prog/STM32_TimerInterrupt#2]
Hello,

I'd like to implement a very simple 2.4 MHz clock divider using STM32_TimerInterrupt. I'm able to achieve this simply in STM32CubeIDE. However I want to do the same thing in Arduino because I like all the other libraries that make programming my STM32 much easier than using the CubeIDE. The input clock is 72 MHz and I use a counter period of 29 and a pulse of 15 on TIM_CH1 in PWM Generation mode. I've been looking through the documentation to figure out how to achieve this with STM32_TimerInterrupt but I am having trouble. Is it possible?

![image](https://user-images.githubusercontent.com/71182580/100495346-90db0a80-30ff-11eb-9a48-e238887a4918.png)

Thanks
Noah

**Comment by khoih-prog** [comment]
Thanks for your interest in the library.

Currently, it's designed to support only Timer Interrupt, **not the PWM-related functions**, although the programming code is very similar.

It can be achieved easily by programming directly and you can search the Servo or PWM-related documentations for guidance.

If there are many more interests in this feature, I'll think about develop such a library.

Good Luck,
