### ISSUE TITLE
Center Aligned PWM output MODE

### ISSUE THREAD

**Issue by roccotarocco** [khoih-prog/STM32_TimerInterrupt#3]
Hi,
very nice development, thanks for effort.
What about the possibility to activate from Arduino IDE the Center Aligned output mode?
Thanks
TG

**Comment by khoih-prog** [comment]
Thanks for your nice words.

Currently, the library is written just to provide TimerInterrupt-related features, and doesn't support PWM for controlling Servos, etc. You certainly can use this library to achieve that `Center Aligned output mode`, with some more tailor-made codes.

You can 

1. Have a look at [**STM32 Servo library**](https://github.com/stm32duino/Arduino_Core_STM32/tree/master/libraries/Servo) to use for Servo or 
2. Even use STM32 `HardwareTimer` directly to program the `Center Aligned output mode`.

I definitely will add the `Center Aligned` and PWM support later to this library if there are more similar `Center Aligned` and PWM requests, or even write STM32_ISR-based Servo library, similar to [**ESP8266_ISR_Servo**](https://github.com/khoih-prog/ESP8266_ISR_Servo) and [**ESP32_ISR_Servo**](https://github.com/khoih-prog/ESP32_ISR_Servo).

Anyway, I have to close the issue now.
