### ISSUE TITLE
NOT ABLE TO COMPILE 

### ISSUE THREAD

**Issue by eklavyainfo** [khoih-prog/STM32_TimerInterrupt#4]
In member function 'bool STM32TimerInterrupt::setFrequency(float, timerCallback)':
C:\Users\Ravi\Documents\Arduino\libraries\STM32_TimerInterrupt\src/STM32TimerInterrupt.h:99:33: error: invalid conversion from 'timerCallback' {aka 'void (*)()'} to 'void (*)(HardwareTimer*)' [-fpermissive]
   99 |       _hwTimer->attachInterrupt(callback);
      |                                 ^~~~~~~~
      |                                 |
      |                                 timerCallback {aka void (*)()}
In file included from C:\Users\Ravi\AppData\Local\Arduino15\packages\STM32\hardware\stm32\1.8.0\cores\arduino/stm32/analog.h:45,
                 from C:\Users\Ravi\AppData\Local\Arduino15\packages\STM32\hardware\stm32\1.8.0\cores\arduino/board.h:8,
                 from C:\Users\Ravi\AppData\Local\Arduino15\packages\STM32\hardware\stm32\1.8.0\cores\arduino/wiring.h:41,
                 from C:\Users\Ravi\AppData\Local\Arduino15\packages\STM32\hardware\stm32\1.8.0\cores\arduino/Arduino.h:32,
                 from C:\Users\Ravi\AppData\Local\Temp\arduino_build_146343\sketch\TimerInterruptTest.ino.cpp:1:

**Comment by khoih-prog** [comment]
It's possible that you are using old STM32 core **v1.8.0** ( to follow [**Prerequisites**](https://github.com/khoih-prog/STM32_TimerInterrupt#prerequisites)  and use **v1.9.0**) or **you modify the example not correctly.**

This is the current compile result of [**TimerInterruptTest**](https://github.com/khoih-prog/STM32_TimerInterrupt/tree/main/examples/TimerInterruptTest)

![Selection_658](https://user-images.githubusercontent.com/57012152/106656656-f537a180-6568-11eb-8e49-293e6b2b688a.png)

Next time, I won't spend and wast my time time to deal with these matters until these are followed
1. [**Prerequisites**](https://github.com/khoih-prog/STM32_TimerInterrupt#prerequisites)
2. [**How to create a Minimal, Reproducible Example**](https://stackoverflow.com/help/minimal-reproducible-example)
