### ISSUE TITLE
My 1602-LCD display random 

### ISSUE THREAD

**Issue by herunur** [khoih-prog/STM32_TimerInterrupt#5]
I have tried this STM32_TimerInterrupt, but why my 1602-LCD display any random character after few times.

code:
//Still error on LCD but Internal board LED likely ok
//These define's must be placed at the beginning before #include "TimerInterrupt.h"
#define TIMER_INTERRUPT_DEBUG      1
#include "ESP32TimerInterrupt.h"
#ifndef LED_BUILTIN
#define LED_BUILTIN       2         // Pin D2 mapped to pin GPIO2/ADC12 of ESP32, control on-board LED
#endif
#define PIN_D23           23        // Pin D23 mapped to pin GPIO23/VSPI_MOSI of ESP32

// include the library code for LCD 1602:
#include <LiquidCrystal.h>
 
// initialize the library with the numbers of the interface pins
LiquidCrystal lcd(19, 23, 18, 17, 16, 15);

#define Blink_interval  500            // Set at top of source code file
unsigned long previousMillis = 0;
bool BlankOnOff = false;
int in = 0;
 
//ISR Interupt Service Routine by Timer 16 bit
void IRAM_ATTR TimerHandler0(void)
{
  static bool toggle0 = false;
  static bool started = false;

  if (!started)
  {
    started = true;
    pinMode(LED_BUILTIN, OUTPUT);
  }

  #if (TIMER_INTERRUPT_DEBUG > 0)
  Serial.println("ITimer0Interupt: millis() = " + String(millis()));
  #endif
  
  //timer interrupt toggles pin LED_BUILTIN
  digitalWrite(LED_BUILTIN, toggle0);
  toggle0 = !toggle0;

//Text Blink on LCD    
    BlinkText("Read ", 12, 1);

}

#define TIMER0_INTERVAL_MS        2000

// Instantiate ESP32 timer0 and 1
ESP32Timer ITimer0(0);
//ESP32Timer ITimer1(1);

void setup()
{
  Serial.begin(115200);
  Serial.println("\nStarting di Setup");
  
  // Using ESP32  => 80 / 160 / 240MHz CPU clock ,
  // For 64-bit timer counter
  // For 16-bit timer prescaler up to 1024

  // Interval in microsecs
  if (ITimer0.attachInterruptInterval(TIMER0_INTERVAL_MS * 1000, TimerHandler0))
    Serial.println("Starting  ITimer0 Setup OK, millis() = " + String(millis()));
  else
    Serial.println("Can't set ITimer0 Setup. Select another freq. or timer");

/*
  // Interval in microsecs    
  if (ITimer1.attachInterruptInterval(TIMER1_INTERVAL_MS * 1000, TimerHandler1))
    Serial.println("Starting  ITimer1 OK, millis() = " + String(millis()));
  else
    Serial.println("Can't set ITimer1. Select another freq. or timer");    
*/

  // set up the LCD's number of columns and rows:
  lcd.begin(16, 2);
  // Print a message to the LCD.
  lcd.print("TEST LCD Timer Int");

}

//Function Text Blink
void BlinkText(char *msgtxt, int kolom, int baris) {

    noInterrupts(); // no interupt after this, critical, time-sensitive code here

  unsigned long currentMillis = millis();
  lcd.setCursor(kolom, baris);
  if(currentMillis - previousMillis > Blink_interval)   {
    previousMillis = currentMillis;
    if(BlankOnOff){
      for(in = 1; in < strlen(msgtxt); in++) {
        lcd.print(" ");
      } //End For
    } // End If
    else {
      lcd.print(msgtxt);
    } //End Else
    BlankOnOff = !BlankOnOff;
  } //End If

     interrupts();   // enable interupt, other code here

} // End BlinkText
 
void loop()
{
  noInterrupts(); // no interupt after this, critical, time-sensitive code here

  // set the cursor to column 0, line 1
  // (note: line 1 is the second row, since counting begins with 0):
  lcd.setCursor(0, 1); 
  lcd.print("Loop:");
  // print the number of seconds since reset:
  lcd.print(millis() / 1000); 

   interrupts();   // enable interupt, other code here

}

**Comment by khoih-prog** [comment]
> I have tried this STM32_TimerInterrupt, but why my 1602-LCD display any random character after few times.
> 

and 

> #include "ESP32TimerInterrupt.h"

How can this mistake and/or hasty post happens?

As you know in programming, even a **small mistake** can create a severe headache, and sometimes is **never found and fixed** (such as Windows BSOD). This `random character` is a symptom of stray pointers and bad code.The origin can be anywhere, such as your code and/or one of many libraries you're using.

I have no time to deal with your problem as only you can figure out. Will spend some time only you prove that there is some bug of this library.

Good Luck,
